### ISSUE TITLE
Function for numericals

### ISSUE THREAD

**Issue by Santhan9999** [maxbachmann/JaroWinkler#16]
I use compare.string or compare.exact for data in object format, and these functions find probable matches. But for the numerical data compare.numeric seems to be not working anymore. I have the construction year of the building column, I need a function to find most near years matches.

Thanks in advance.

**Comment by maxbachmann** [comment]
I am completely unsure what you are asking. The APIs (`compare.string`, `compare.exact` and `compare.numeric`) do not exist in this library. Can you clarify what you mean?

**Comment by Santhan9999** [comment]
Sorry that it wasn't clear. I have issues with the 'compare.numeric' API for my context. Below is the code I tried,

#compare.numeric('Building construction year', 'Building construction year', scale=10, offset=0, method='linear', label=None)

my context:
I am trying to link records in two datasets, my specific objective with this function is to identify possible matches with records nearby years. For example, Dataset1 has a record with 1996 and this algorithm should match Dataset2's records with 1996 and also nearby years such as 1995, 1997 etc.

I hope it is clear. Thanks

**Comment by maxbachmann** [comment]
Are you sure you did open this issue on the correct repository? This is the python library jarowinkler, which does not have this API.

**Comment by Santhan9999** [comment]
Yes. This issue is regarding Jaro-Winkler. My question is it possible to perform 'this function' using the Jaro-Winkler function, using a similar API ?

If not, please let me know, I will understand this is too irrelevant issue to this repository.

**Comment by Santhan9999** [comment]
Yes, you are correct. Jaro Winkler calculates the similarity of the texts but maybe not numerical especially years similarity.

**Comment by maxbachmann** [comment]
Yes it is unaware of numerical and just treats them as characters, so e.g. `1999` is very similar to `1998`, but not similar to `2000` at all. This is simply not what the jaro winkler distance was created to do. It is largely a metric to compare sequences which might incorporate typos like e.g. census data.
